app:
  security-server-name: NOTION-SECURITY
spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  application:
    name: notion-gateway
logging:
  level:
    org:
      springframework:
        security: DEBUG